-- PERSONAS
insert into "RONNY"."PERSONAS" (ID_PERSONA, NOMBRE, APELLIDO, FECHA_NACIMIENTO, E_MAIL, TELEFONO_CELULAR, ESTADO, ROL )
  values ('01','Ronny','Blanco','03/02/1991','ron123@gmail.com','7766-5443','inactivo','paciente');
  
insert into "RONNY"."PERSONAS" (ID_PERSONA, NOMBRE, APELLIDO, FECHA_NACIMIENTO, E_MAIL, TELEFONO_CELULAR, ESTADO, ROL )
  values ('02','Wilber','Hernandez','05/05/1994','wil321@gmail.com','7665-5643','inactivo','paciente');
  
insert into "RONNY"."PERSONAS" (ID_PERSONA, NOMBRE, APELLIDO, FECHA_NACIMIENTO, E_MAIL, TELEFONO_CELULAR, ESTADO, ROL )
  values ('03','Homero','Simpson','13/12/1996','homersimp48@yahoo.es','7666-6666','activo','doctor');
  
insert into "RONNY"."PERSONAS" (ID_PERSONA, NOMBRE, APELLIDO, FECHA_NACIMIENTO, E_MAIL, TELEFONO_CELULAR, ESTADO, ROL)
  values ('04','Ervin','Romero','06/07/2000','erv456@gmail.com','7000-1122','inactivo','paciente');
  
insert into "RONNY"."PERSONAS" (ID_PERSONA, NOMBRE, APELLIDO, FECHA_NACIMIENTO, E_MAIL, TELEFONO_CELULAR, ESTADO, ROL)
  values ('05','Alex','Bonilla','02/05/1990/','albo12@gmail.com','7343-2312','activo','paciente');
  
insert into "RONNY"."PERSONAS" (ID_PERSONA, NOMBRE, APELLIDO, FECHA_NACIMIENTO, E_MAIL, TELEFONO_CELULAR, ESTADO, ROL)
  values ('06','Napo','Guevara','16/06/1997','nagu@gmail.com','7980-9878','activo','paciente');
  
insert into "RONNY"."PERSONAS" (ID_PERSONA, NOMBRE, APELLIDO, FECHA_NACIMIENTO, E_MAIL, TELEFONO_CELULAR, ESTADO, ROL )
  values ('07','Nestor','Argueta','23/01/1995','near23@gmail.com','7565-6565','inactivo','paciente');
  
insert into "RONNY"."PERSONAS" (ID_PERSONA, NOMBRE, APELLIDO, FECHA_NACIMIENTO, E_MAIL, TELEFONO_CELULAR, ESTADO, ROL)
  values ('08','Josue','Ayala','12/11/1989','joay45@gmail.com','7555-6565','activo','paciente');
  
insert into "RONNY"."PERSONAS" (ID_PERSONA, NOMBRE, APELLIDO, FECHA_NACIMIENTO, E_MAIL, TELEFONO_CELULAR, ESTADO, ROL)
  values ('09','Kelly','Hernandez','28/04/1998','kelly28@gmail.com','7677-7778','activo','paciente');
  
insert into "RONNY"."PERSONAS" (ID_PERSONA, NOMBRE, APELLIDO, FECHA_NACIMIENTO, E_MAIL, TELEFONO_CELULAR, ESTADO, ROL )
  values ('10','Maria','Andrade','07/06/1997','maan12@gmail.com','7665-4321','inactivo','paciente');
  
-- TIPOS DE EXAMENES

INSERT INTO "RONNY"."TIPOSEXAMENES" (ID_TIPO_EXAMEN, NOMBRE_EXAMEN, DESCRIPCION, MUESTRA) 
  VALUES ('01', 'General de Orina' , 'examen general de orina', '--');
  
INSERT INTO "RONNY"."TIPOSEXAMENES" (ID_TIPO_EXAMEN, NOMBRE_EXAMEN, DESCRIPCION, MUESTRA) 
  VALUES ('02', '' , '', '');  

INSERT INTO "RONNY"."TIPOSEXAMENES" (ID_TIPO_EXAMEN, NOMBRE_EXAMEN, DESCRIPCION, MUESTRA) 
  VALUES ('03', '' , '', '');
  
INSERT INTO "RONNY"."TIPOSEXAMENES" (ID_TIPO_EXAMEN, NOMBRE_EXAMEN, DESCRIPCION, MUESTRA) 
  VALUES ('04', '' , '', '');

INSERT INTO "RONNY"."TIPOSEXAMENES" (ID_TIPO_EXAMEN, NOMBRE_EXAMEN, DESCRIPCION, MUESTRA) 
  VALUES ('05', '' , '', '');
  
INSERT INTO "RONNY"."TIPOSEXAMENES" (ID_TIPO_EXAMEN, NOMBRE_EXAMEN, DESCRIPCION, MUESTRA) 
  VALUES ('06', '' , '', '');

INSERT INTO "RONNY"."TIPOSEXAMENES" (ID_TIPO_EXAMEN, NOMBRE_EXAMEN, DESCRIPCION, MUESTRA) 
  VALUES ('07', '' , '', '');
  
INSERT INTO "RONNY"."TIPOSEXAMENES" (ID_TIPO_EXAMEN, NOMBRE_EXAMEN, DESCRIPCION, MUESTRA) 
  VALUES ('08', '' , '', '');
  
INSERT INTO "RONNY"."TIPOSEXAMENES" (ID_TIPO_EXAMEN, NOMBRE_EXAMEN, DESCRIPCION, MUESTRA) 
  VALUES ('09', '' , '', '');
  
INSERT INTO "RONNY"."TIPOSEXAMENES" (ID_TIPO_EXAMEN, NOMBRE_EXAMEN, DESCRIPCION, MUESTRA) 
  VALUES ('10', '' , '', '');